# Basic
title: Reinhard Huang
subtitle: 大道至简，知易行难
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 他们我行我素，从不墨守成规；他们桀骜不驯，从不安于现状；他们乐于分享，却又谦卑内敛；他们是大众眼中的怪咖，是疯子；但唯有他们自己知道——不疯魔不成活；他们的名字叫极客！
creator: @Reinhard Huang

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
#nav:
#    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: reinhardhuang
    github: xiemotongye
    twitter: xiejuntongye
    mail: xiemotongye@gmail.com

# Google Analytics
ga:
    id: UA-106091114-1
    host: reinhardhuang.com
